# .github/workflows/deploy.yml
name: Deploy to Production
on:
  push:
    branches:
      - main    # main 브랜치에 push될 때 실행

env:
  AWS_REGION: us-east-1
  S3_BUCKET: jmh-cicd-pri-bucket # 운영 배포용 S3 버킷
  CODE_DEPLOY_APPLICATION: cicd-pub-codedeploy
  CODE_DEPLOY_DEPLOYMENT_GROUP: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws deploy push \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION }} \
            --s3-location s3://${{ env.S3_BUCKET }}/deploy.zip \
            --ignore-hidden-files

      - name: Deploy to Production EC2
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION }} \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP }} \
            --s3-location bucket=${{ env.S3_BUCKET }},key=deploy.zip,bundleType=zip
